### ISSUE TITLE
macOS: PyBluez installation 

### ISSUE THREAD

**Issue by rmoriz** [rfinnie/rdserialtool#1]
Hi,

thanks a lot for this great project!

I was able to install pybluez on 10.14.3 by [manually applying a yet unmerged PR](https://github.com/pybluez/pybluez/pull/223):

```shell
git clone https://github.com/pybluez/pybluez 
cd pybluez
curl https://patch-diff.githubusercontent.com/raw/pybluez/pybluez/pull/223.patch | patch -p1
python3 setup.py install 
```

![image](https://user-images.githubusercontent.com/1527/54025891-3f0c8700-419c-11e9-9068-de8f86afdb49.png)
![image](https://user-images.githubusercontent.com/1527/54025925-5cd9ec00-419c-11e9-8c81-e6f95ed549b9.png)

**Comment by rfinnie** [comment]
Thanks!  I'll update the README to mark that as verified.

Did you also happen to try RFCOMM via /dev/cu* or /dev/tty*?  I've only got one Mac to try on, but in my tests, data from the computer to the UM/DPS will arrive at the device, but data from the device to the computer is never received.

**Comment by dancingmadkefka** [comment]
I tried to install this too but I am having trouble with pybluez too. Not sure if it's just me though.

I get the following affter trying to connect:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/rdserialtool", line 11, in <module>
    load_entry_point('rdserialtool==0.2', 'console_scripts', 'rdserialtool')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rdserialtool-0.2-py3.7.egg/rdserial/tool.py", line 163, in main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rdserialtool-0.2-py3.7.egg/rdserial/tool.py", line 145, in main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rdserialtool-0.2-py3.7.egg/rdserial/device/__init__.py", line 82, in __init__
NotImplementedError: pybluez not available

**Comment by rmoriz** [comment]
@dancingmadkefka did you install pybluez?

**Comment by dancingmadkefka** [comment]
I did, but maybe it's not installed correctly. I used the tip on the issue page for installing. It seemed ok but maybe I can wipe it and try again? 

⁣Get BlueMail for Android ​
